name: myaseapp
description: A secure Flutter login app using Supabase backend
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”— Supabase backend
  supabase_flutter: ^2.5.0

  # ðŸ” Secure local storage
  flutter_secure_storage: ^9.0.0

  # ðŸŒ Connectivity check
  connectivity_plus: ^6.0.3

  http: ^1.2.0
  cupertino_icons: ^1.0.6

  google_sign_in: ^6.2.1

  shared_preferences: ^2.2.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # ðŸŽ¨ App icon
  flutter_launcher_icons: ^0.13.1

  # ðŸŒ¸ Splash screen
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/slide1.jpg
    - assets/images/slide2.jpg
    - assets/images/slide3.jpg



# -----------------------------
# App icon configuration
# -----------------------------
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"


# -----------------------------
# Splash screen configuration
# -----------------------------
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: false
  android_gravity: center

